litmus/urls.py
from django.conf.urls import url
from litmus import views

app_name = 'litmus'
urlpatterns = [
    url(r'^$', views.litmus, name='litmus'),
    url(r'^main$', views.main, name='main'),
    url(r'^colorSearch$', views.colorSearch, name='colorSearch'),
    url(r'^colorInfo/(?P<pk>\d+)/$', views.colorInfo, name='colorInfo'),
    url(r'^colorLibrary$', views.colorLibrary, name='colorLibrary'),

]

zeroth/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from litmus import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.litmus, name='litmus'),
    url(r'^litmus$', views.litmus, name='litmus'),
    url(r'^litmus/', include('litmus.urls', namespace='litmus')),
    
]


litmus/models.py
from django.db import models

# Create your models here.

litmus/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
import time
import os
import json
import math
from .litmus_database import Litmus
from .litmus_search import search_main, search_info
from .color_vector import ColorVector
from .litmus_plot import plot_RGB

def litmus(request):
    return redirect('litmus:main')

def main(request):
    if request.method == "POST":
        word = request.POST['search']
        search = search_main(word)
        if search:
            context = {'word':word, 'search':search}
            return render(request, 'litmus/color_search.html', context)
    context = {'count':'Normal'}
    return render(request, 'litmus/main.html', context)

def colorSearch(request):
    if request.method == "POST":
        word = request.POST['search']
        search = search_main(word)
        # word = 'something'
        if search:
            context = {'word':word, 'search':search}
            return render(request, 'litmus/color_search.html', context)
    context = {'count':'Normal'}
    return render(request, 'litmus/color_search.html', context)

def colorInfo(request, pk): 
    color_id = int(pk)
    litmus = Litmus.get_by_id(color_id)
    hexa = litmus['hexa']
    vector = ColorVector(hexa).all
    search = search_info(color_id)
    message = ""
    context = {'message':message, 'litmus':litmus, 'vector':vector, 'search':search}
    return render(request, 'litmus/color_info.html', context)

def colorLibrary(request):
    db = Litmus.classify_by_group('name', 'ascend')
    total = Litmus.count()
    context = {'colors':db, 'total':total}
    return render(request, 'litmus/color_library.html', context)
    

litmus/templates/litmus/about.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <p>about</p>
</div>

<div class="container">
    <hr>
    <h1>Bootstrap grid examples</h1>
    <p class="lead">Basic grid layouts to get you familiar with building within the Bootstrap grid system.</p>

    <h2>Five grid tiers</h2>
    <p>There are five tiers to the Bootstrap grid system, one for each range of devices we support. Each tier starts at a minimum viewport size and automatically applies to the larger devices unless overridden.</p>

    <div class="row">
    <div class="col-3">.col-3</div>
    <div class="col-3">.col-3</div>
    <div class="col-3">.col-3</div>
    <div class="col-3">.col-3</div>
    </div>

    <div class="row">
    <div class="col-sm-4">.col-sm-4</div>
    <div class="col-sm-4">.col-sm-4</div>
    <div class="col-sm-4">.col-sm-4</div>
    </div>

    <div class="row">
    <div class="col-md-4">.col-md-4</div>
    <div class="col-md-4">.col-md-4</div>
    <div class="col-md-4">.col-md-4</div>
    </div>

    <div class="row">
    <div class="col-lg-4">.col-lg-4</div>
    <div class="col-lg-4">.col-lg-4</div>
    <div class="col-lg-4">.col-lg-4</div>
    </div>

    <div class="row">
    <div class="col-xl-4">.col-xl-4</div>
    <div class="col-xl-4">.col-xl-4</div>
    <div class="col-xl-4">.col-xl-4</div>
    </div>

    <h2>Three equal columns</h2>
    <p>Get three equal-width columns <strong>starting at desktops and scaling to large desktops</strong>. On mobile devices, tablets and below, the columns will automatically stack.</p>
    <div class="row">
    <div class="col-md-4">.col-md-4</div>
    <div class="col-md-4">.col-md-4</div>
    <div class="col-md-4">.col-md-4</div>
    </div>

    <hr>

    <h2>Full width, single column</h2>
    <p class="text-warning">No grid classes are necessary for full-width elements.</p>

    </div>

</div> <!-- /container -->

{% endblock %}

litmus/templates/litmus/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
  <title>Litmus</title>
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}" >  -->
  
  <!-- jQuery CDN -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <!-- Popper.js CDN ( Bootstrap.js 앞에 배치) -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <!-- Bootstrap.js CDN -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
  <!-- Fontawesome CDN -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  
  <!-- Bootstrap Colorpicker -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.3/css/bootstrap-colorpicker.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.3/js/bootstrap-colorpicker.min.js"></script>

  <!-- Plotly CDN -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  <!-- respond.js CDN -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
  
  <!-- <script src="{% static 'scripts/modernizr-2.6.2.js' %}"></script> -->
  <!-- <link rel="shortcut icon" href="url ('static', filename='favicon.ico') " /> -->

  {% block head %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black; padding: 0px">
    <div class="container body-content">
      <a class="navbar-brand" href="{% url 'litmus:main' %}">
      <img src="{% static 'icon/Color Studio-Litmus Project(navi)-20190801.jpg' %}" style="width: 300px; height: auto;" alt="ModenJay Color Studio"/></a>
      <img src="{% static 'icon/Color Studio-Litmus Project(logo)-20190404.jpg' %}" style="width: 120px; height: auto;" alt="McScience"/>
    </div>
  </nav>
   
  <div class="container body-content">
      {% block content %}{% endblock %}
      <hr />
      <footer>
        <div class="jumbotron" style="background-color:rgb(226, 226, 226); padding:5px; padding-left:10px">
          <b style="font-size:9pt">&copy; ModenJay<sup>&reg</sup> Color Studio - Litmus Project</b>
        </div>
      </footer>
  </div>
  
  <!-- jQuery Local -->
  <!-- <script src="{% static 'scripts/jquery-1.10.2.js' %}"></script> -->
  
  <!-- Bootstrap Local -->
  <!-- <script src="{% static 'scripts/bootstrap.js' %}"></script>  -->
  
  <!-- script src="{% static 'scripts/respond.js' %}"></script> -->
  {% block scripts %}{% endblock %}

</body>
</html>

litmus/templates/litmus/color_library.html
{% extends "base.html" %}

{% block head %}
<style>
    #map { height: 600px; width:900px}
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
        }
</style>
{% endblock %}

{% block content %}

<br>
<div class="container-fluid text-center">
    <div class="row content">
        <!-- Title -->
        <div class="col-sm-8 text-left"> 
            <h3>List of Colors</h3>
            <p>Total {{total}} Colors in Current Library</p>
        <!-- Sort -->
        <!--
            <div class="dropdown">
                <button class="btn btn btn-outline-dark font-weight-bold dropdown-toggle" type="button" id="dropdownSort" 
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort by</button>
                <div class="dropdown-menu" aria-labelledby="dropdownSort">
                  <a class="dropdown-item" href="#sortByColorGroup">Color Group</a>
                  <a class="dropdown-item" href="#sortByColorName">Color Name</a>
                </div>
            </div>
        -->
        </div>
        <!-- Setting of Link Button -->
        <div class="col-sm-2" style="text-align:right">
            <p></p>     
            <p></p>
            <p></p>
        </div>
        <div class="col-sm-2" style="text-align:right">
            <p><a class="btn btn-info btn-sm border-light" style="background-color:indigo; width:110pt"
                href="{% url 'litmus:main' %}">Color Search</a></p>
            <p></p>
        </div>
    </div>
</div>
<hr>
<div class="container" id="sortByColorGroup">
    <div class="card">
        {% for key, value in colors.items %}
            <div class="card-header" id="heading{{key}}" style="padding:0px; padding-left:15px">
                <h5 class="mb-0 d-flex justify-content-between align-items-center">
                    <span style="font-size:14pt; padding:0px">{{ key.capitalize }} &ensp;</span>
                    {% if key == "Red" %}
                    <button class="btn btn-dark btn-sm collapsed" style="width:100px;" data-toggle="collapse" data-target="#collapse{{key}}" aria-expanded="true" aria-controls="#collapse{{key}}">
                    {% else %}
                    <button class="btn btn-dark btn-sm collapsed" style="width:100px;" data-toggle="collapse" data-target="#collapse{{key}}" aria-expanded="false" aria-controls="#collapse{{key}}">
                    {% endif %}
                    <span class="badge badge-dark" style="font-size:12pt; width:50px; text-align:right">{{value.count}}</span>
                    &ensp; &nabla;
                    </button>   
                </h5>  
            </div>
            {% if key == "Red" %}
            <div id="collapse{{key}}" class="collapse show" aria-labelledby="heading{{key}}" >
            {% else %}
            <div id="collapse{{key}}" class="collapse show" aria-labelledby="heading{{key}}" >
            {% endif %}
            
            <div class="card-body" style="padding:5px; padding-left:20px; "></div>
            {% for litmus in value.litmus %}
                <div style="display: inline-block; padding-left:5px; ">
                    {% if litmus.depth == "Dark"  or litmus.depth == "Deep" %}
                        <p><a class="btn btn-primary btn-block border-light"
                            style="width: 80px; height: 40px; font-size:8pt; text-align:left; padding:5px; color:white; background-color:{{litmus.hexa}};"
                            href="{% url 'litmus:colorInfo' pk=litmus.id %}">
                            {{ litmus.name|slice:':12' }}
                        </a></p>
                    {% else %}
                        <p><a class="btn btn-default btn-block border-light font-weight-bold"
                            style="width: 80px; height: 40px; font-size:8pt; text-align:left; padding:5px; color:black; background-color:{{litmus.hexa}}"
                            href="{% url 'litmus:colorInfo' pk=litmus.id %}">
                            {{ litmus.name|slice:':12' }}
                        </a></p>
                    {% endif %}
                </div>
            {% endfor %}
            <br>
            </div>
        {% endfor %}
    </div>
    <br>
    <h5>Geo Map</h5>
    <hr>
    <div id="map"></div>
</div>  
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCr7uqzPRQYrFASLrIVkMbK8yCk6vbavtQ&callback=initMap"
></script>

{% endblock %}

{% block scripts %}
<script>
    $(function () {
        $('#color_picker').colorpicker({
            format: 'hex',
        });
        $('#color_picker').colorpicker().on('changeColor', function(e) {
            document.getElementById("search_input").value = e.color.toHex().toUpperCase();

        });
    });
</script>
<script>
    var map;
    function initMap() {
        var map_center = {lat: 34, lng: 130}; 
        var map = new google.maps.Map(document.getElementById('map'), {zoom: 1.6, center: map_center});
        // var marker = new google.maps.Marker({position: map_center, map: map, title:"title"});
        
        var locations = [
            {% for key, value in colors.items %}
            {% for litmus in value.litmus %}
            ["{{litmus.id}}", {{litmus.geo.0}}, {{litmus.geo.1}}, "{{litmus.name}}", "{{litmus.hexa}}", "{{item.case}}"],
            {% endfor %}
            {% endfor %}
        
        ]
        for (var i = 0; i < locations.length; i++) {
            var marker = new google.maps.Marker({ 
                position: {lat: locations[i][1], lng: locations[i][2]}, 
                map: map,
                label: {
                    color: 'black',
                    fontWeight: 'bold',
                    fontSize: '11px',
                    text: locations[i][3]
                },
                icon: {
                    path: google.maps.SymbolPath.CIRCLE,
                    scale : 6,
                    strokeWeight : 2,
                    fillColor: locations[i][4],
                    fillOpacity: 1.0,
                    strokeColor: 'gray',
                    // anchor: new google.maps.Point(0, 0),
                    labelOrigin: new google.maps.Point(0, 2)
                },
            }); 
        }
    }
</script>

{% endblock %}

litmus/templates/litmus/color_search.html
{% extends "base.html" %}

{% block head %}
<style>
    #map { height: 480px; width:720px}
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
        }
</style>
{% endblock %}

{% block content %}

<br>
<div class="container-fluid text-center">
    <div class="row content">
        <!-- Title -->
        <div class="col-sm-4 text-left"> 
            <h4>Color Search</h4>
            <p></p>
            <br>
        </div>
        <!-- Setting of Search Button -->
        <div class="col-sm-4" style="text-align:right">
            <form class="form-inline" style="text-align:center" action="{% url 'litmus:colorSearch' %}" id="color_search" method="POST">
                {% csrf_token %}
                <div class="form-group" style="text-align:center">
                    <input type="text"  name="search" id="search_input" class="form-control input-group colorpicker-component" style="text-align:left" placeholder="color name or code">
                    <button type="submit" onkeydown="enterkey();" name="submit" class="btn btn-Warning"><i class="fas fa-search"></i></button>   
                </div>
            </form>        
        </div>
        <div class="col-sm-2" style="text-align:right">
            <p></p>
            <p></p>
            <p></p>
        </div>
    </div>
    
</div>

<div class="container">
    {% if search.identical.count %}
        <br>
        <h5>Colors Identical to "{{word}}" <span class="badge badgesuccess" style="font-size:10pt; text-align:center">{{search.identical.count}}</span></h5>
        <hr>
        {% for item in search.identical.list %}
        <div style="display: inline-block;">
            <p><a class="btn btn-primary btn-block border-light"
                style="width: 150px; height: 45px; font-size:8pt; font-weight:{{item.litmus.text.font}}; text-align:left; padding:5px; color:{{item.litmus.text.color}}; background-color:{{item.litmus.hexa}};"
                href="{% url 'litmus:colorInfo' pk=item.id %}">
                {{ item.litmus.name }}
            </a></p>
        </div>
        {% endfor %}
        <br><br>
    {% endif %}

    {% if search.neighbor.count %}
        <br>
        <h5>Colors Neighbor to "{{word}}" <span class="badge badge-success" style="width:40px; font-size:10pt; text-align:center">{{search.neighbor.count}}</span></h5>
        <hr>
        {% for item in search.neighbor.list %}
        <div style="display: inline-block;">
            <p><a class="btn btn-primary btn-block border-light"
                style="width: 150px; height: 45px; font-size:8pt; font-weight:{{item.litmus.text.font}}; text-align:left; padding:5px; color:{{item.litmus.text.color}}; background-color:{{item.litmus.hexa}};"
                href="{% url 'litmus:colorInfo' pk=item.id %}">
                {{ item.litmus.name }}<br>d={{item.distance|floatformat:4}}
            </a></p>
        </div>
        {% endfor %}
        <br><br>
    {% endif %}
    {% if search.cell.count %}
        <br>
        <h5>Colors in "{{word|slice:'1:'}}" RGB Cell &ensp;<span class="badge badge-success" style="width:40px; font-size:10pt; text-align:center">{{search.cell.count}}</span></h5>
        <hr>
        {% for item in search.cell.list %}
        <div style="display: inline-block;">
            <p><a class="btn btn-primary btn-block border-light"
                style="width: 150px; height: 45px; font-size:8pt; font-weight:{{item.litmus.text.font}}; text-align:left; padding:5px; color:{{item.litmus.text.color}}; background-color:{{item.litmus.hexa}};"
                href="{% url 'litmus:colorInfo' pk=item.id %}">
                {{ item.litmus.name }}
            </a></p>
        </div>
        {% endfor %}
        <br><br>
    {% endif %}
    {% if search.family.count %}
        <br>
        <h5>Family colors of "{{word|slice:'1:'}}" <span class="badge badge-success" style="width:40px; font-size:10pt; text-align:center">{{search.family.count}}</span></h5>
        <hr>
        {% for item in search.family.list %}
        <div style="display: inline-block;">
            <p><a class="btn btn-primary btn-block border-light"
                style="width: 150px; height: 45px; font-size:8pt; font-weight:{{item.litmus.text.font}}; text-align:left; padding:5px; color:{{item.litmus.text.color}}; background-color:{{item.litmus.hexa}};"
                href="{% url 'litmus:colorInfo' pk=item.id %}">
                {{ item.litmus.name }}
            </a></p>
        </div>
        {% endfor %}
        <br><br>
    {% endif %}
    {% if search.match.count %}
        <br>
        <h5>Colors including word "{{word}}" <span class="badge badge-success" style="width:40px; font-size:10pt; text-align:center">{{search.match.count}}</span></h5>
        <hr>
        {% for item in search.match.list %}
        <div style="display: inline-block;">
            <p><a class="btn btn-primary btn-block border-light"
                style="width: 150px; height: 45px; font-size:8pt; font-weight:{{item.litmus.text.font}}; text-align:left; padding:5px; color:{{item.litmus.text.color}}; background-color:{{item.litmus.hexa}};"
                href="{% url 'litmus:colorInfo' pk=item.id %}">
                {{ item.litmus.name}}
            </a></p>
        </div>
        {% endfor %}
        <br><br>
    {% endif %}
    {% if word %}
    <br><br>
    
    <h5>Geo Map</h5>
    <hr>
    <div id="map"></div>
    {% endif %}
</div>  
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCr7uqzPRQYrFASLrIVkMbK8yCk6vbavtQ&callback=initMap"
></script>

{% endblock %}

{% block scripts %}

<script>
    var map;
    function initMap() {
        var map_center = {lat: 38, lng: 138}; 
        var map = new google.maps.Map(document.getElementById('map'), {zoom: 1.4, center: map_center});
        // var marker = new google.maps.Marker({position: map_center, map: map, title:"title"});
        
        var locations = [
            {% for key, value in search.items %}
            {% for item in value.list %}
            ["{{item.id}}", {{item.litmus.geo.0}}, {{item.litmus.geo.1}}, "{{item.litmus.name}}", "{{item.litmus.hexa}}", "{{item.case}}"],
            {% endfor %}
            {% endfor %}
        ];
        for (var i = 0; i < locations.length; i++) {
            if (locations[i][5] == 'supernova') {
                var marker = new google.maps.Marker({ 
                    position: {lat: locations[i][1], lng: locations[i][2]}, 
                    map: map,
                    label: {
                        color: 'black',
                        fontWeight: 'bold',
                        fontSize: '11px',
                        text: locations[i][3]
                    },
                    icon: {
                        path: google.maps.SymbolPath.BACKWARD_CLOSED_ARROW,
                        scale : 3,
                        strokeWeight : 1,
                        fillColor: locations[i][4],
                        fillOpacity: 1.0,
                        strokeColor: 'black',
                        // anchor: new google.maps.Point(0, 0),
                        labelOrigin: new google.maps.Point(0, 2)
                    },
                });
            } else {
                var marker = new google.maps.Marker({ 
                    position: {lat: locations[i][1], lng: locations[i][2]}, 
                    map: map,
                    label: {
                        color: 'black',
                        fontWeight: 'bold',
                        fontSize: '11px',
                        text: locations[i][3]
                    },
                    icon: {
                        path: google.maps.SymbolPath.CIRCLE,
                        scale : 4,
                        strokeWeight : 2,
                        fillColor: locations[i][4],
                        fillOpacity: 1.0,
                        strokeColor: 'black',
                        // anchor: new google.maps.Point(0, 0),
                        labelOrigin: new google.maps.Point(0, 2)
                    },
                });
            }
        }
    }
</script>
{% endblock %}

litmus/templates/litmus/main.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container-fluid text-center" style="text-align:center; padding:0px; padding-top:100px; padding-bottom:100px">
    <!-- Title -->
    <img src="{% static 'icon/Color Studio-Litmus Project(title)-20190404.jpg' %}" style="width: 320px; height: auto;" alt="Search Colors"/>

    <!-- Search with Color Picker-->
    <br><br><br><br>
    <form class="form-inline justify-content-center"  action="{% url 'litmus:main' %}" id="color_search" method="POST">
        {% csrf_token %}
        
        <div class="form-group" >
            <div style="display: inline-block">
                <input type="text"  name="search" id="search_input" class="form-control input-group colorpicker-component" style="width: 200px; height: auto; text-align:left" placeholder="color name or code">
                <button type="submit" name="submit" class="btn btn-Warning"><i class="fas fa-search"></i></button>   
            </div>
        </div>  
    </form>
</div>

<div class="container-fluid text-center" style="text-align:center; padding:50px">
</div>

{% endblock %}